create table if not exists public.recommendation_settings (
  user_id uuid primary key references public.users (id) on delete cascade,
  receive_mode text not null default 'approved' check (receive_mode in ('all', 'approved', 'off')),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.recommendation_permissions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id) on delete cascade,
  target_user_id uuid not null references public.users (id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'blocked', 'rejected')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, target_user_id)
);

create table if not exists public.recommendations (
  id bigint generated by default as identity primary key,
  sender_user_id uuid not null references public.users (id) on delete cascade,
  receiver_user_id uuid not null references public.users (id) on delete cascade,
  profile_id uuid references public.profiles (id) on delete set null,
  profile_slug text,
  source_profile_name text,
  content_type text not null default 'profile' check (content_type in ('profile', 'photo', 'video', 'reel')),
  content_uri text,
  expires_at timestamptz not null default (timezone('utc', now()) + interval '24 hours'),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.recommendation_reactions (
  id uuid primary key default gen_random_uuid(),
  recommendation_id bigint not null references public.recommendations (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  reaction text not null check (reaction in ('like', 'fire', 'wow', 'love')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (recommendation_id, user_id)
);

create index if not exists recommendation_permissions_target_idx
on public.recommendation_permissions (target_user_id, status);

create index if not exists recommendations_receiver_idx
on public.recommendations (receiver_user_id, expires_at, created_at);

create index if not exists recommendations_sender_idx
on public.recommendations (sender_user_id, created_at);

create index if not exists recommendation_reactions_user_idx
on public.recommendation_reactions (user_id);

drop trigger if exists recommendation_settings_set_updated_at on public.recommendation_settings;
create trigger recommendation_settings_set_updated_at
before update on public.recommendation_settings
for each row
execute function public.set_updated_at();

drop trigger if exists recommendation_permissions_set_updated_at on public.recommendation_permissions;
create trigger recommendation_permissions_set_updated_at
before update on public.recommendation_permissions
for each row
execute function public.set_updated_at();

drop trigger if exists recommendation_reactions_set_updated_at on public.recommendation_reactions;
create trigger recommendation_reactions_set_updated_at
before update on public.recommendation_reactions
for each row
execute function public.set_updated_at();

alter table public.recommendation_settings enable row level security;
alter table public.recommendation_permissions enable row level security;
alter table public.recommendations enable row level security;
alter table public.recommendation_reactions enable row level security;
